#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
import serial
from serial.tools import list_ports
from vuserial import trep_to_string

app = QtWidgets.QApplication(sys.argv)

window = QtWidgets.QWidget()

iso_date_validator = QtGui.QRegExpValidator(QtCore.QRegExp(r'\d\d\d\d-[0-1]\d-[0-3]\d'), window)

layout = QtWidgets.QGridLayout()

portselect = QtWidgets.QComboBox()
for port in list_ports.comports(include_links=True):
    try:
        ser = serial.Serial(port)
        portselect.addItem(ser.portstr)
        ser.close()
    except serial.serialutil.SerialException:
        continue
layout.addWidget(QtWidgets.QLabel('serial port'), 0, 0)
layout.addWidget(portselect, 0, 1)

firstDate = QtWidgets.QLineEdit()
firstDate.setValidator(iso_date_validator)
layout.addWidget(QtWidgets.QLabel('first date'), 1, 0)
layout.addWidget(firstDate, 1, 1)

lastDate = QtWidgets.QLineEdit()
lastDate.setValidator(iso_date_validator)
layout.addWidget(QtWidgets.QLabel('last date'), 2, 0)
layout.addWidget(lastDate, 2, 1)

trepbox = {}
for t in range(3, 7):
    trepbox[t] = QtWidgets.QCheckBox(trep_to_string(t))
    trepbox[t].setCheckState(True)
    layout.addWidget(trepbox[t], t, 0)


logger = QtWidgets.QTextEdit()
layout.addWidget(logger, 8, 0, 8, 1)
logger.setReadOnly(True)


class LogToWidget:
    def write(self, string):
        logger.append(string)


sys.stdout = LogToWidget()
sys.stderr = LogToWidget()

window.setLayout(layout)
print('mockup/guitest')
print('does nothing')


window.setWindowTitle('loadvu')
window.show()

sys.exit(app.exec_())
